spring:
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  datasource:
    main:
      url: jdbc:postgresql://localhost:5433/postgres?currentSchema=streaming
      driver-class-name: org.postgresql.Driver
      username: user
      password: password
  application:
    name: api
  jpa:
    hibernate:
      database-platform: org.hibernate.dialect.PostgreSQLDialect
      ddl-auto: create-drop
    properties:
      hibernate:
        hbm2ddl:
          auto: create-drop
  sql:
    init:
      continue-on-error: true

kafka:
  producer:
    bootstrap-servers: >-
      localhost:29092
  consumer:
    bootstrap-servers: >-
      localhost:29092
  target-topics:
    Orchestrator-Api:
      name: slivoviy.orchestrator-api
      concurrency: 1

server:
  port: 8082
  servlet:
    context-path: /
  tomcat:
    basedir: /tmp/tomcat