spring:
  application:
    name: inference

kafka:
  producer:
    bootstrap-servers: >-
      localhost:29092
  consumer:
    bootstrap-servers: >-
      localhost:29092
  target-topics:
    Runner-Inference:
      name: slivoviy.runner-inference
      concurrency: 1
  source-topics:
    Inference-Runner:
      name: slivoviy.inference-runner
      concurrency: 1

server:
  port: 8085
  servlet:
    context-path: /
  tomcat:
    basedir: /tmp/tomcat